version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: ferryflow_db
    environment:
      POSTGRES_USER: ferryflow
      POSTGRES_PASSWORD: ferryflow_dev_2024
      POSTGRES_DB: ferryflow_dev
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ferryflow -d ferryflow_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:17-alpine
    container_name: ferryflow_test_db
    environment:
      POSTGRES_USER: ferryflow
      POSTGRES_PASSWORD: ferryflow_test_2024
      POSTGRES_DB: ferryflow_test
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ferryflow -d ferryflow_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data: